### ISSUE TITLE
Calling multiple trees at the same page

### ISSUE THREAD

**Issue by kozfelipe** [pandeyz/treejs#1]
When I call multiple trees at the same page, only the last call renders the tree content

**Comment by pandeyz** [comment]
Please let me know are you calling multiple trees with the different ID's or you are using the CLASS selector?

**Comment by kozfelipe** [comment]
Ive tried both, with ID and CLASS selectors
ps.: it works as json though my issue is with html response

**Comment by kozfelipe** [comment]
I managed to work around it using json

**Comment by pandeyz** [comment]
Its working fine with the json form with two diferent ID's. I have tested it.  Please check the attached screenshot.

![ex](https://user-images.githubusercontent.com/20596667/32171342-c7217a9e-bd9d-11e7-91e8-22cc2099adad.png)

**Comment by kozfelipe** [comment]
Yes indeed, with json it works. My issue was with html response tho.

![image](https://user-images.githubusercontent.com/25208457/32180933-66dfe38c-bd7a-11e7-87ae-dd65e6c7d873.png)
